/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers = [
    {
        x: 0,
        z: 0,
        name: 'toto'
    },
    {
        x: 1293,
        z: 1309,
        name: 'tutu'
    },
    {
        x: -153,
        z: 1137,
        name: 'tata'
    },
    {
        x: 869,
        z: 1876,
        name: 'kiki'
    },
    {
        x: -756,
        z: -476,
        name: 'stop'
    },
    {
        x: -564,
        z: -453,
        name: 'coucou'
    },
    {
        x: -1929,
        z: -1179,
        name: 'tatatatata'
    },
    {
        x: -346,
        z: 387,
        name: 'tutututu'
    }
]